#   _____  _                    _        _____
#  /  ___|(_)                  | |      |  ___|
#  \ `--.  _  _ __ ___   _ __  | |  ___ | |__    ___   ___
#  `--. \| || '_ ` _ \ | '_ \ | | / _ \|  __|  / __| / _ \
# /\__/ /| || | | | | || |_) || ||  __/| |___ | (__ | (_) |
# \____/ |_||_| |_| |_|| .__/ |_| \___|\____/  \___| \___/
#                     | |
#                     |_|

#╔═════════════════════════════════════╗
#║                  MySQL              ║
#╚═════════════════════════════════════╝
mysql: false

#╔═════════════════════════════════════╗
#║                  Currency           ║
#╚═════════════════════════════════════╝
currency: $